Add cockpit bearer token script and unit file
code-ready/snc pull request #494
Opened 2021-12-17 10:37 UTC by praveenkumar

This patch should enable cockpit to use with bearer token and
make sure only user level service is running.

- https://gist.github.com/gbraad/c556d82394ca0dcc333e9609974fcaf8

It is using https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot
doc for adding the unit file for core user.

2021-12-17 10:37 UTC, praveenkumar commented
/hold

Till bundle tested by @gbraad

2021-12-17 11:10 UTC, cfergeau approved these changes
Some more explanations could be useful, looks good otherwise.

2021-12-17 11:10 UTC, cfergeau commented on fcos-config.yaml
> +      mode: 0755
Does this need to be executable? the default permissions are probably good enough?

2021-12-17 11:10 UTC, cfergeau commented on fcos-config.yaml
> +      # Add systemd unit for the cockpit bearer token
Fwiw, it's really not obvious what in the unit file is related to a 'bearer token'. I see a cockpit service being started as the core user, this is reflected in the name of the unit file `cockpit-core-user.service`. If this is key to connecting to cockpit without auth, maybe it's worth giving more details how this works in the PR?

2021-12-17 11:10 UTC, cfergeau commented on fcos-config.yaml
> +          # FIXME: should be random
maybe this could be fixed?

2021-12-18 04:42 UTC, gbraad commented
Will do this weekend or Monday. Had to focus on getting the pullsecret stored after the setup phase.

2021-12-18 07:35 UTC, gbraad commented on fcos-config.yaml
> +          # FIXME: should be random
We need to do that in sync with CRC, as the tray-electron would need to read this bearer and use for authentication. Let's start with this as part of the test and then implement a file or http API to retrieve the needed bearer.

2021-12-18 07:36 UTC, gbraad commented on fcos-config.yaml
> +          if [ "$(echo "$response" | jq -r .response)" != "Bearer Y29yZQ==" ]; then
this is the value that needs to be synced between the image and https://github.com/gbraad/podman-desktop/blob/9d13968a58eab54985fbabe23f58f0f3d9937d9a/main.js#L15

2021-12-18 07:37 UTC, gbraad commented on fcos-config.yaml
> +          # FIXME: should be random
https://github.com/code-ready/tray-electron/issues/24#issue-1082456798

2021-12-20 07:17 UTC, gbraad requested changes
This needs the cockpit service disabled, else port 9090 is claimed.

2021-12-20 15:08 UTC, gbraad commented
```
Created symlink /var/home/core/.config/systemd/user/multi-user.target.wants/cockpit-core-user.service → /var/home/core/.config/systemd/user/cockpit-core-user.service.
Unit /var/home/core/.config/systemd/user/cockpit-core-user.service is added as a dependency to a non-existent unit multi-user.target.
```

the dependency is probably not correct

2021-12-21 05:01 UTC, gbraad approved these changes

2021-12-21 05:02 UTC, merged