Podman: Add arch info to podman download URI
code-ready/snc pull request #528
Opened 2022-05-16 07:01 UTC by praveenkumar

From 4.x the name of tarball now includes the arch details and this
PR is to update it.

- https://github.com/containers/podman/releases/tag/v4.0.2

2022-05-16 07:40 UTC, gbraad approved these changes

2022-05-16 08:34 UTC, cfergeau requested changes
This PR/the commit logs are missing details explaining *why* we need podman 4 support. Was the f35 image we use upgraded to podman4? Was the stable fcos image updated to f36 with podman4 now that f36 is released? Or is this podman 4 change depending on an upcoming PR?

2022-05-16 08:40 UTC, cfergeau commented
> Was the stable fcos image updated to f36 with podman4 now that f36 is released?

Apparently it is not this, I just ran `podman run --rm quay.io/coreos/coreos-installer:release download -s stable` and this ends with:
```
Read disk 663.6 MiB/663.6 MiB (100%)
gpg: Signature made Fri May  6 21:54:33 2022 UTC
gpg:                using RSA key 787EA6AE1147EEE56C40B30CDB4639719867C58F
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   4  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 4u
gpg: Good signature from "Fedora (35) <fedora-35-primary@fedoraproject.org>" [ultimate]
./fedora-coreos-35.20220424.3.0-metal.x86_64.raw.xz
```

2022-05-16 12:26 UTC, praveenkumar commented
Hold is now till fcos-36 is in stable stream.

2022-05-16 12:31 UTC, cfergeau approved these changes
Might be useful to add to the commti log that the stable fcos image is now fedora 36, which ships podman 4 so that everyone understands why we are making this change now.
Apart from this, ACK from me once fcos actually switches to f36.

2022-05-25 04:35 UTC, praveenkumar commented
/retest

2022-05-25 06:14 UTC, praveenkumar commented
/unhold

2022-05-25 06:58 UTC, praveenkumar commented
Now it is blocked by https://github.com/containers/podman/issues/14353

2022-05-25 07:46 UTC, cfergeau commented
> /unhold

Context: Fedora CoreOS stable release is now based on fedora 36, which ships podman 4

2022-05-25 11:51 UTC, praveenkumar commented
/unhold

I will put another PR for https://github.com/containers/podman/issues/14353 one once we have https://github.com/containers/podman/issues/14201#issuecomment-1137065060 4.1.0 static bits as expected.

2022-05-25 11:51 UTC, merged